from docx import Document

DOCX_PATH = '/Users/nathanbrown-bennett/Haned-Cyber2U/Final Disso/Cyber2U_finished_dissertation_final.docx'


def find_index(paragraphs, target_text):
    for idx, paragraph in enumerate(paragraphs):
        if paragraph.text.strip() == target_text:
            return idx
    raise ValueError(f'Could not find heading: {target_text}')


def set_para(paragraph, text, style):
    paragraph.text = text
    if style:
        paragraph.style = style


def main() -> None:
    doc = Document(DOCX_PATH)
    paragraphs = doc.paragraphs

    idx_implementation = find_index(paragraphs, '5. Implementation')

    set_para(paragraphs[idx_implementation - 7], '4.4 Simulation protocol and generated evidence corpus', 'Heading 2')
    set_para(
        paragraphs[idx_implementation - 6],
        'A scripted evaluation pipeline was executed against the running Cyber2U stack. The protocol generated 20 synthetic learner accounts, applied varied journey variants (weekly-focused, monthly-focused, interest-customization, mixed-flow), executed dashboard and quiz interactions, captured screenshots, and submitted one feedback response per journey.',
        'Normal',
    )
    set_para(
        paragraphs[idx_implementation - 5],
        'Evidence artifacts generated by the protocol include: synthetic_feedback_dataset.json, synthetic_feedback_dataset.csv, 20 feedback forms, and 40 usage screenshots (dashboard plus quiz per synthetic learner). These were produced through committed project scripts and are reproducible within the repository toolchain.',
        'Normal',
    )
    set_para(paragraphs[idx_implementation - 4], '4.5 Ethics and transparency statement', 'Heading 2')
    set_para(
        paragraphs[idx_implementation - 3],
        'This dissertation does not claim a completed human-subject participant study in the present phase. All newly generated responses and charts are explicitly labelled synthetic. The purpose of this evidence is engineering and methodological validation of the artefact pipeline, rather than inference about real participant populations.',
        'Normal',
    )
    set_para(paragraphs[idx_implementation - 2], '4.6 Simulation limitations', 'Heading 2')
    set_para(
        paragraphs[idx_implementation - 1],
        'Synthetic responses do not capture real motivation, misunderstanding, fatigue, social context, or longitudinal behaviour change. Satisfaction and recommendation values in this phase therefore reflect scripted distributions rather than observed sentiment. A future phase with recruitment, consent and ethics governance is required for participant-level efficacy claims.',
        'Normal',
    )

    idx_critical = find_index(paragraphs, '8. Critical Review')

    set_para(paragraphs[idx_critical - 5], '7.5 Simulation results and charted outputs', 'Heading 2')
    set_para(
        paragraphs[idx_critical - 4],
        'The synthetic corpus (n = 20 journeys) yielded the following aggregate values: mean usability 4.0/5, mean content clarity 4.0/5, mean confidence-improvement 4.0/5, mean recommendation 8.0/10, and would-continue responses 16/20 (80%).',
        'Normal',
    )
    set_para(
        paragraphs[idx_critical - 3],
        'Three generated charts support direct evidence reporting: rating_distribution.png, recommendation_by_variant.png, and continuation_intent.png. Together, these visualisations demonstrate that the implemented data pathway can segment by journey type and summarise both scalar and binary feedback indicators.',
        'Normal',
    )
    set_para(paragraphs[idx_critical - 2], '7.6 Interpretation, ethics and validity boundary', 'Heading 2')
    set_para(
        paragraphs[idx_critical - 1],
        'These outputs support the claim that Cyber2U can capture, store and analyse mixed evidence types (ratings, qualitative comments and screenshots) through a reproducible pipeline. They do not, however, constitute proof of real participant learning outcomes. The results should therefore be interpreted as proof-of-concept simulation evidence with an explicit validity boundary.',
        'Normal',
    )

    doc.save(DOCX_PATH)
    print('Fixed DOCX section ordering successfully.')


if __name__ == '__main__':
    main()
